name: Spring-Petclinic.Docker

on:
  push:
    branches: [ master, playground ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml      
    
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        echo $HOME/Library/Caches
    
    - name: build, scan and tag image
      run: |
        docker build -f ./Dockerfile -t srivatsamarichi/spring-petclinic/spring-petclinic:${{ github.run_number }} .
        trivy --exit-code 0 --severity MEDIUM,HIGH srivatsamarichi/spring-petclinic/spring-petclinic:${{ github.run_number }}
    
    - name: push image to dockerhub
      run: |
        docker push srivatsamarichi/spring-petclinic/spring-petclinic:${{ github.run_number }}
